#!/usr/bin/env python
##############################################################
# This code is part of the MAterials Simulation Toolkit (MAST)
# 
# Maintainer: Tam Mayeshiba
# Last updated: 2014-04-25
##############################################################

import sys, os

from MAST.utility.finite_size_scaling import GenSC
from MAST.utility import Metadata
from MAST.utility import MASTError

if __name__ == '__main__':
    if not os.path.exists("POSCAR"):
        print "No POSCAR file. Only POSCAR files are accepted."
        sys.exit(-1)
    if len(sys.argv) > 1:
        mindefdist = float(sys.argv[1])
    else:
        mindefdist = 4
    if len(sys.argv) > 2:
        maxnumatoms = int(sys.argv[2])
    else:
        maxnumatoms = 1000
    import pymatgen
    mystructure = pymatgen.io.vaspio.Poscar.from_file("POSCAR").structure
    LMNlist = GenSC.genLMN(mystructure, mindefdist, maxnumatoms)
    GenSC.genSCs(mystructure, LMNlist)
    sys.exit()

